site_name: Rojo Documentation
site_description: Documentation home Rojo, a tool for enabling professional development tools on Roblox.
site_url: https://rojo.space/docs
repo_name: rojo-rbx/rojo.space
repo_url: https://github.com/rojo-rbx/rojo.space

theme:
  name: material
  palette:
    primary: 'Red'
    accent: 'Red'

nav:
  - Home: index.md
  - Why Rojo?: why-rojo.md
  - Get Help with Rojo: help.md
  - Rojo Alternatives: rojo-alternatives.md
  - Installing Rojo: installation.md
  - Rojo 6:
    - Creating a Game with Rojo: 6.x/new-game.md
    - Porting an Existing Game to Rojo: 6.x/existing-game.md
    - Rojo Workflows: 6.x/workflows.md
    - Project Format: 6.x/project-format.md
    - Sync Details: 6.x/sync-details.md
  - Rojo 0.5.x:
    - Guide:
      - Creating a Game with Rojo: 0.5.x/guide/new-game.md
      - Porting an Existing Game to Rojo: 0.5.x/guide/existing-game.md
      - Migrating from 0.4.x to 0.5.x: 0.5.x/guide/migrating-to-epiphany.md
    - Reference:
      - Fully vs Partially Managed Rojo: 0.5.x/reference/full-vs-partial.md
      - Project Format: 0.5.x/reference/project-format.md
      - Sync Details: 0.5.x/reference/sync-details.md
    - Rojo Internals:
      - Internals Overview: 0.5.x/internals/overview.md
  - Rojo 0.4.x:
    - Getting Started:
      - Creating a Project: 0.4.x/getting-started/creating-a-project.md
    - Sync Details: 0.4.x/sync-details.md

plugins:
  - search
  - redirects:
      redirect_maps:
        'latest/index.md': https://rojo.space/docs/
        '0.5.x/index.md': https://rojo.space/docs/
        '0.4.x/index.md': https://rojo.space/docs/
        '0.5.x/why-rojo.md': https://rojo.space/docs/why-rojo/
        '0.4.x/why-rojo.md': https://rojo.space/docs/why-rojo/
        '0.5.x/help.md': https://rojo.space/docs/help/
        '0.5.x/rojo-alternatives.md': https://rojo.space/docs/rojo-alternatives/
        '0.5.x/guide/installation.md': https://rojo.space/docs/installation/
        '0.4.x/getting-started/installation.md': https://rojo.space/docs/installation/

extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true